### PR TITLE
Resolve #429, #439, #461, #466

### LINKED ISSUE #429: Better state classification for transfer history
1. sendTxState === 'Pending' => 'SEND_PENDING'
2. sendTxState === 'Confirmed'
   (a) receiveTxState === 'Pending' => 'SEND_CONFIRMED_RECEIVE_PENDING' 
   (b) receiveTxState === 'Confirmed' => 'SEND_CONFIRMED_RECEIVE_CONFIRMED'
   (c) receiveTxState === 'Failed' => 'SEND_CONFIRMED_RECEIVE_FAILURE'
   (d) receiveTxState === null => 'SEND_CONFIRMED_RECEIVE_NOT_INITIATED'
   (d) receiveTxState === null => 'SEND_CONFIRMED_RECEIVE_NOT_INITIATED'
3. sendTxState === 'Confirmed'
   (a) cancelTxState === 'Pending' => 'SEND_CONFIRMED_CANCEL_PENDING' 
   (b) cancelTxState === Confirmed' => 'SEND_CONFIRMED_CANCEL_CONFIRMED'
   (c) cancelTxState === 'Failed' => 'SEND_CONFIRMED_CANCEL_FAILURE'
4. sendTxState === 'Failed' => 'SEND_FAILURE'
5. sendTxState === 'Expired' => 'SEND_EXPIRED'

In the transfer history, show the following

* SEND_PENDING => 'Sending'
* SEND_FAILURE => 'Send Failed'
* SEND_EXPIRED => 'Expired'
* SEND_CONFIRMED_RECEIVE_PENDING => 'Sent'
* SEND_CONFIRMED_RECEIVE_FAILURE => 'Accept Failed'
* SEND_CONFIRMED_RECEIVE_CONFIRMED => 'Accepted'
* SEND_CONFIRMED_RECEIVE_NOT_INITIATED => 'Sent'
* SEND_CONFIRMED_CANCEL_PENDING => 'Cancelling'
* SEND_CONFIRMED_CANCEL_CONFIRMED => 'Cancelled'
* SEND_CONFIRMED_CANCEL_Failure => 'Cancel Failed'

### LINKED ISSUE #439: Retrieve and use last used address when accepting transfer

### PR DESCRIPTION
**Pull request by InVincible2016**
- Retrieve and use last used address when accepting transfer

### CODE REVIEW

File: src/apis.js [hunk 1]
```diff
@@ -88,18 +88,82 @@ async function getPrefilledAccount () {
...
+    var rv = await apiTransfer.post('/transfer', {
+      action: 'GET_LAST_USED_ADDRESS',
+      googleId: googleId
+    })
+    let ledgerWallet = { crypto: {} }
+    let metamaskWallet = { crypto: {} }
+    let driveWallet = { crypto: {} }
+    let wallet = {}
+    const { ledger, metamask, drive } = rv.data
+    if (ledger) {
```
Comment (timothywangdev) [inline src/apis.js]: Too much redundant code, suggestion:

```js
var lastUsedAddress = ['metamask', 'ledger'].reduce((lastUsedAddressObj, walletType) => {
  let addressByCryptoType = walletCryptoSupports[walletType]
    .map(cryptoTypeData => cryptoTypeData.cryptoType)
    .reduce((obj, cryptoType) => {
      if (!!data[walletType] && !!data[walletType][cryptoType]) {
        obj[cryptoType] = { address: data[walletType][cryptoType].address }
      }
      return obj
    }, {})

  lastUsedAddressObj[walletType] = { crypto: addressByCryptoType }
  return lastUsedAddressObj
}, {})
```

* Example:

```js
var data = {
  googleId: '114203282241002032395',
  lastUpdatedCryptoType: 'ethereum',
  lastUpdatedWalletType: 'ledger',
  ledger: {
    bitcoin: {
      address: '2MzMFoiGAHkTPkrtCX4WE1CZPtrMsY7wtVw',
      timestamp: '1557250242'
    },
    ethereum: {
      address: '0xD36Efe3b8A914b57e81676113b510E5c116EAf5e',
      timestamp: '1557344036'
    }
  }
}
```

* output
```js
{ metamask: { crypto: {} },
  ledger:
   { crypto:
      { ethereum: { address: '0xD36Efe3b8A914b57e81676113b510E5c116EAf5e' },
        bitcoin: { address: '2MzMFoiGAHkTPkrtCX4WE1CZPtrMsY7wtVw' } } } }
```

File: src/actions/transferActions.js [hunk 2]
```diff
@@ -692,17 +692,63 @@ async function _getTransferHistory () {
...
-        // pending receive
-        state = 'pending'
-      } else {
-        // cancelled
-        state = 'cancelled'
+    const { sendTxState, receiveTxState, cancelTxState } = item
+    switch (sendTxState) {
+      case 'Pending': {
+        // SEND_PENDING
+        state = 'Sending'
```
Comment (timothywangdev) [inline src/actions/transferActions.js]: export a list of transfer states for other components to use:

```js
const TRANSFER_STATES = {
  SEND_CONFIRMED_RECEIVE_PENDING: 'SEND_CONFIRMED_RECEIVE_PENDING',
  ...
}
```
Make sure to export the constants

return the corresponding state constant instead of string, i.e.
```js
return TRANSFER_STATES.SEND_CONFIRMED_RECEIVE_PENDING
```
