### PR TITLE
Resolve #165, #173, #178, #179, #182, #183, #187, #188, #191

### LINKED ISSUE #165: Integrate Btc into Chainsfer

### LINKED ISSUE #173: Get and save account info when connect with Ledger

### LINKED ISSUE #179: Use bip38 for btc encryption instead of openpgp

### LINKED ISSUE #182: Estimate Btc transaction fee

### LINKED ISSUE #187: Implement new wallet structure
```js
wallet: {
    driveWallet: {
      fileId: null,
      content: []
    },
    ledger: {
      connected: [boolean],
      network: [string],
      crypto: {
        "ethereum": {
          [accountIndex]: [integer]: {
            address: [string],
            balance [BN] // balance is a BN object in smallest token unit,
          },
        "bitcoin": {
          [accountIndex]: [integer]: {
            balance [BN] // balance is a BN object in smallest token unit
            nextAddressIndex: [integer],
            nextChangeIndex: [integer],
            addresses: [{ // addresses that contains utxos
              path: [string],
              publicKeyInfo: {},
              utxos: [Array of utxos]
            }...],
            lastBlockHeight: [integer],
            lastUpdate: [unix timestamp]
          },
      }
    },
    metamask: {
      connected:  [boolean],
      network: [string],
      crypto: {
        "ethereum": {
          [accountIndex]: [integer]: {
            address: [string],
            balance [BN] // balance is a BN object in smallest token unit,
          },
        "dai": {
          [accountIndex]: [integer]: {
            address: [string],
            balance [BN] // balance is a BN object in smallest token unit,
          },
        }
      }
} 
```

### LINKED ISSUE #191: double-click crypto when ledger is chosen causes app to crash

### PR DESCRIPTION
**Pull request by InVincible2016**
Resolve #165: Integrate Btc to Chainsfer
- Chainsfer can now send out btc.

Resolve #173, #178
- Get and save account info to localStorage after first connected with
ledger Nano S
- Improve transfer flow for btc on ledger. Much fast transfer process
now.

Resolve #179: Use bip38 for encryption instead of openpgp

Resolve #182, #183
- Add transaction cost estimation to Btc
- Rename gasCost to txCost, including all reference and displays.

Resolve #187, #188 
Resolve #191

### CODE REVIEW

File: src/actions/transferActions.js [hunk 1]
```diff
@@ -10,7 +10,11 @@ import moment from 'moment'
 import { Base64 } from 'js-base64'
 import ERC20 from '../ERC20'
 import { getCrypto } from '../tokens'
+import bitcore from 'bitcore-lib'
+import wif from 'wif'
+import bip38 from 'bip38'
 
+const WIF_VERSION = 0xEF // testnet:0xEF, mainnet:0x80
```
Comment (timothywangdev) [inline src/actions/transferActions.js]: use .env for selection

File: src/actions/transferActions.js [hunk 2]
```diff
@@ -38,64 +42,112 @@ async function _getGasCost (txRequest) {
...
     if (cryptoType === 'ethereum') {
       let wei = window._web3.utils.toWei(transferAmount.toString(), 'ether')
       txObj = {
-        from: fromWallet.accounts[0].address,
+        from: fromWallet.crypto[cryptoType][0].address,
         to: escrow.address,
         value: wei
       }
     } else if (cryptoType === 'dai') {
+      console.log('fromWallet', fromWallet.crypto[cryptoType])
```
Comment (timothywangdev) [inline src/actions/transferActions.js]:
```suggestion
```

File: src/actions/transferActions.js [hunk 3]
```diff
@@ -348,9 +409,10 @@ function cancelTransferTransactionHashRetrieved (txRequest) {
 
 function submitTx (txRequest) {
   return (dispatch, getState) => {
+    const accountInfo = getState().walletReducer.wallet.ledger.crypto[txRequest.cryptoType][0]
```
Comment (timothywangdev) [inline src/actions/transferActions.js]: what if wallet.ledger.crypto = null ?

Comment (timothywangdev) [reply src/actions/transferActions.js]: should this step depend on txRequest's cryptoType?

Comment (timothywangdev) [reply src/actions/transferActions.js]: suggestion: 

```js
txRequest.accountInfo = txRequest.cryptoType === 'bitcoin' ? getState().walletReducer.wallet.ledger.crypto[txRequest.cryptoType][0]
```

File: src/actions/transferActions.js [hunk 4]
```diff
@@ -373,10 +435,13 @@ function cancelTransfer (txRequest) {
   }
 }
 
-function getGasCost (txRequest) {
-  return {
-    type: 'GET_GAS_COST',
-    payload: _getGasCost(txRequest)
+function getTxCost (txRequest) {
+  return (dispatch, getState) => {
+    const addressPool = getState().walletReducer.wallet.ledger.crypto[txRequest.cryptoType][0].addresses
```
Comment (timothywangdev) [inline src/actions/transferActions.js]: see above comment

File: src/actions/walletActions.js [hunk 5]
```diff
@@ -1,19 +1,27 @@
...
-import BN from 'bn.js'
 import { goToStep } from './navigationActions'
 import { Base64 } from 'js-base64'
 import { getTransferData } from '../drive.js'
 import ERC20 from '../ERC20'
 
 const ledgerNanoS = new LedgerNanoS()
 
+function syncLedgerAccountInfo (cryptoType, accountIndex = 0) {
+  return (dispatch, getState) => {
```
Comment (timothywangdev) [inline src/actions/walletActions.js]: what are (dispatch, getState) doing here?

File: src/components/CancelReviewComponent.jsx [hunk 6]
```diff
@@ -18,21 +18,21 @@ class CancelReviewComponent extends Component {
...
     const { open } = this.state
-    const { transfer, escrowWallet, gasCost, receipt, actionsPending } = this.props
+    const { transfer, escrowWallet, txCost, receipt, actionsPending } = this.props
     if (transfer) {
       const { sendingId, sendTxHash, transferAmount, cryptoType } = transfer
       if (!actionsPending.cancelTransfer && // cancelTransfer is not currently running
-          !receipt && // cancelTransfer has not been called
-          open && // cancel popup is currently focused
-          escrowWallet.decryptedWallet) { // escrowWallet has been decrypted
+        !receipt && // cancelTransfer has not been called
```
Comment (timothywangdev) [inline src/components/CancelReviewComponent.jsx]: do we have styling issues here? if not, do not change these lines

File: src/components/CancelReviewComponent.jsx [hunk 7]
```diff
@@ -103,11 +103,11 @@ class CancelReviewComponent extends Component {
...
-                  <CircularProgress
-                    size={24}
-                    color='primary'
-                    className={classes.buttonProgress}
-                  />}
+                    <CircularProgress
+                      size={24}
+                      color='primary'
+                      className={classes.buttonProgress}
+                    />}
```
Comment (timothywangdev) [inline src/components/CancelReviewComponent.jsx]: no need to change

File: src/components/CancelReviewComponent.jsx [hunk 8]
```diff
@@ -153,108 +153,108 @@ class CancelReviewComponent extends Component {
                   </Grid>
                   <Grid item className={classes.reviewItem}>
                     <Typography className={classes.reviewSubtitle} align='left'>
-                     From
+                      From
```
Comment (timothywangdev) [inline src/components/CancelReviewComponent.jsx]: no change

File: src/components/CancelReviewComponent.jsx [hunk 9]
```diff
@@ -153,108 +153,108 @@ class CancelReviewComponent extends Component {
...
                     </Typography>
                     <Typography className={classes.reviewContent} align='left'>
                       {sender}
                     </Typography>
                   </Grid>
                   <Grid item className={classes.reviewItem}>
                     <Typography className={classes.reviewSubtitle} align='left'>
-                     To
+                      To
```
Comment (timothywangdev) [inline src/components/CancelReviewComponent.jsx]: no change

File: src/components/CancelReviewComponent.jsx [hunk 10]
```diff
@@ -153,108 +153,108 @@ class CancelReviewComponent extends Component {
...
                     </Typography>
                     <Typography className={classes.reviewContent} align='left'>
                       {destination}
                     </Typography>
                   </Grid>
                   <Grid item className={classes.reviewItem}>
                     <Typography className={classes.reviewSubtitle} align='left'>
-                     Amount
+                      Amount
```
Comment (timothywangdev) [inline src/components/CancelReviewComponent.jsx]: no change

File: src/components/CancelReviewComponent.jsx [hunk 11]
```diff
@@ -153,108 +153,108 @@ class CancelReviewComponent extends Component {
...
-                    </Typography>
-                    <Typography className={classes.reviewContent} align='left'>
-                      {!actionsPending.getGasCost && gasCost
-                        ? <Typography className={classes.reviewContent} align='left'>
-                          {parseFloat(gasCost.costInEther) + parseFloat(transferAmount)} ETH
-                        </Typography>
-                        : <CircularProgress size={18} color='primary' />}
-                    </Typography>
-                  </Grid>
+                    <Grid item className={classes.reviewItem}>
```
Comment (timothywangdev) [inline src/components/CancelReviewComponent.jsx]: Remove total cost section

File: src/components/CancelReviewComponent.jsx [hunk 12]
```diff
@@ -153,108 +153,108 @@ class CancelReviewComponent extends Component {
...
+                            {parseFloat(txCost.costInStandardUnit) + parseFloat(transferAmount)} {getCryptoSymbol(cryptoType)}
+                          </Typography>
+                          : <CircularProgress size={18} color='primary' />}
+                      </Typography>
+                    </Grid>
                   }
                   <Grid item className={classes.reviewItem}>
                     <Typography className={classes.reviewSubtitle} align='left'>
-                     Sent on
+                      Sent on
```
Comment (timothywangdev) [inline src/components/CancelReviewComponent.jsx]: no change

File: src/components/CancelReviewComponent.jsx [hunk 13]
```diff
@@ -153,108 +153,108 @@ class CancelReviewComponent extends Component {
...
+                    <Grid item className={classes.reviewItem}>
+                      <Typography className={classes.reviewSubtitle} align='left'>
+                        {hasReceived && 'Received on'}
+                        {hasCancelled && 'Cancelled on'}
+                      </Typography>
+                      <Typography className={classes.reviewContent} align='left'>
+                        {hasReceived && moment.unix(receiveTimestamp).format('MMM Do YYYY, HH:mm:ss')}
+                        {hasCancelled && moment.unix(cancelTimestamp).format('MMM Do YYYY, HH:mm:ss')}
+                      </Typography>
+                    </Grid>
```
Comment (timothywangdev) [inline src/components/CancelReviewComponent.jsx]: no change

File: src/components/CancelReviewComponent.jsx [hunk 14]
```diff
@@ -153,108 +153,108 @@ class CancelReviewComponent extends Component {
...
-                    </Typography>
-                  </Grid>
+                    <Grid item>
+                      <Typography color='primary' className={classes.etherscanLink} align='left'>
+                        <MuiLink
+                          target='_blank'
+                          rel='noopener'
+                          href={`https://rinkeby.etherscan.io/tx/${(hasReceived && receiveTxHash) || (hasCancelled && cancelTxHash)}`}>
+                          Check status on Etherscan
+                        </MuiLink>
```
Comment (timothywangdev) [inline src/components/CancelReviewComponent.jsx]: no change

File: src/components/CancelReviewComponent.jsx [hunk 15]
```diff
@@ -153,108 +153,108 @@ class CancelReviewComponent extends Component {
...
-              >
-                 Cancel Transfer
-              </Button>
+          <Grid item className={classes.btnSection}>
+            <Grid container direction='row' justify='center' spacing={24}>
+              <Grid item>
+                <Button
+                  fullWidth
+                  color='primary'
+                  size='large'
```
Comment (timothywangdev) [inline src/components/CancelReviewComponent.jsx]: no change

File: src/components/ReceiptComponent.jsx [hunk 16]
```diff
@@ -65,18 +65,18 @@ class ReceiptComponent extends Component {
...
+                    Transaction Fee
                   </Typography>
                   <Typography className={classes.reviewContent} align='left'>
-                    {`${gasCost.costInEther} ETH`}
+                    {`${txCost.costInStandardUnit} ${getCryptoSymbol(cryptoSelection)}`}
                   </Typography>
                 </Grid>
                 <Grid item className={classes.reviewItem}>
                   <Typography className={classes.reviewSubtitle} align='left'>
                     Total Cost
```
Comment (timothywangdev) [inline src/components/ReceiptComponent.jsx]: Remove total cost section

File: src/components/ReceiveReceiptComponent.jsx [hunk 17]
```diff
@@ -59,18 +59,18 @@ class ReceiveReceiptComponent extends Component {
...
+                    {`${txCost.costInStandardUnit} ${getCryptoSymbol(cryptoSelection)}`}
                   </Typography>
                 </Grid>
                 <Grid item className={classes.reviewItem}>
                   <Typography className={classes.reviewSubtitle} align='left'>
                     You will receive*
                   </Typography>
                   <Typography className={classes.reviewContent} align='left'>
-                    {`${parseFloat(transferAmount) - parseFloat(gasCost.costInEther)} ETH`}
+                    {`${parseFloat(transferAmount) - parseFloat(txCost.costInStandardUnit)} ${getCryptoSymbol(cryptoSelection)}`}
```
Comment (timothywangdev) [inline src/components/ReceiveReceiptComponent.jsx]: isn't costInStandardUnit already a float number

File: src/components/ReceiveReviewComponent.jsx [hunk 18]
```diff
@@ -10,33 +10,33 @@ import { getCryptoSymbol } from '../tokens'
...
   componentDidMount () {
     // refresh gas cost
     const { transfer } = this.props
-    this.props.getGasCost({ cryptoType: transfer.cryptoType })
+    this.props.getTxCost({ cryptoType: transfer.cryptoType })
   }
 
   render () {
-    const { classes, wallet, transfer, actionsPending, gasCost } = this.props
+    const { classes, wallet, transfer, cryptoSelection, actionsPending, txCost } = this.props
```
Comment (timothywangdev) [inline src/components/ReceiveReviewComponent.jsx]: no need for cryptoSelection

File: src/components/ReviewComponent.jsx [hunk 19]
```diff
@@ -80,21 +80,21 @@ class ReviewComponent extends Component {
...
+                  {!actionsPending.getTxCost && txCost
                     ? <Typography className={classes.reviewContent} align='left'>
-                      {gasCost.costInEther} ETH
+                      {txCost.costInStandardUnit} {getCryptoSymbol(cryptoSelection)}
                     </Typography>
                     : <CircularProgress size={18} color='primary' />}
                 </Grid>
                 <Grid item>
                   <Typography className={classes.reviewSubtitle} align='left'>
                     Total Cost
```
Comment (timothywangdev) [inline src/components/ReviewComponent.jsx]: remove total cost section

File: src/components/ReviewComponent.jsx [hunk 20]
```diff
@@ -21,18 +21,18 @@ class ReviewComponent extends Component {
...
+      txCost: txCost
     })
   }
 
   componentDidMount () {
     // refresh gas cost
-    const { cryptoSelection } = this.props
-    this.props.getGasCost({ cryptoType: cryptoSelection })
+    const { cryptoSelection, getTxCost } = this.props
+    getTxCost({ cryptoType: cryptoSelection })
```
Comment (timothywangdev) [inline src/components/ReviewComponent.jsx]: do we have sufficient params for getTxCost? see https://github.com/ventureum/Chainsfer/blob/fa1cfab611a818c0f368af9dea63361ea0fed612/src/actions/transferActions.js#L30

File: src/ledgerSigner/index.js [hunk 21]
```diff
@@ -42,30 +48,74 @@ class LedgerNanoS {
...
+          [cryptoType]: {
+            [accountIndex]: {
+              address: address,
+              balance: balance
+            }
+          }
+        }
+      case 'dai':
+      // TODO: add supoort for dai
+        address = await this.getEthAddress(accountIndex)
```
Comment (timothywangdev) [inline src/ledgerSigner/index.js]: duplicated code, consider merge this into ethereum-based coins section

```js
case 'ethereum':
case 'dai':
  // load eth balance
case 'dai':
  // load dai balance
```

File: src/ledgerSigner/index.js [hunk 22]
```diff
@@ -42,30 +48,74 @@ class LedgerNanoS {
...
       return {
         connected: true,
-        accounts: [{
-          address: await this.getEthAddress(0),
-          balance: {
-            ethereum: await this.getBalance(0)
-          }
-        }],
-        network: networkIdMap[process.env.REACT_APP_NETWORK_NAME]
+        network: cryptoType === 'bitcoin' ? 'testnet' : networkIdMap[process.env.REACT_APP_NETWORK_NAME]
```
Comment (timothywangdev) [inline src/ledgerSigner/index.js]: use .env value instead of "testnet"

File: src/ledgerSigner/index.js [hunk 23]
```diff
@@ -245,6 +295,234 @@ class LedgerNanoS {
     const rv = await targetContract.methods[methodName](...functionParams).call()
     return rv
   }
+
+  getUtxoDetails = async (txHash) => {
+    const details = await axios.get(`${ledgerApiUrl}/transactions/${txHash}/hex`)
+    console.log(details)
```
Comment (timothywangdev) [inline src/ledgerSigner/index.js]:
```suggestion
```

File: src/ledgerSigner/index.js [hunk 24]
```diff
@@ -245,6 +295,234 @@ class LedgerNanoS {
...
+  syncBtcAccountInfo = async (accountIndex) => {
+    const btcLedger = await this.getBtcLedger()
+    let i = 0
+    let totalBalance = 0
+    let addresses = []
+    let gap = 0
+    let utxos = []
+    let changeIndex = 0
+    let addressIndex = 0
+    while (gap < 5) {
```
Comment (timothywangdev) [inline src/ledgerSigner/index.js]: why using gap=5?

Comment (timothywangdev) [reply src/ledgerSigner/index.js]: also, looks like internal and external address discovery are in the same loop, shouldn't they be in separate loops?

File: src/ledgerSigner/index.js [hunk 25]
```diff
@@ -245,6 +295,234 @@ class LedgerNanoS {
...
+    return accountData
+  }
+
+  getLastBlockHeight = async () => {
+    const rv = (await axios.get(blockcypherBaseUrl)).data
+    return rv.height
+  }
+
+  // Function to estimate Tx size
+  // Referrenced from https://github.com/LedgerHQ/ledger-wallet-webtool/blob/094d3741527e181a626d929d56ab4a515403e4a0/src/TransactionUtils.js#L10
```
Comment (timothywangdev) [inline src/ledgerSigner/index.js]: good comment!

File: src/reducers/transferReducer.js [hunk 26]
```diff
@@ -43,11 +43,11 @@ export default function (state = initialState, action) {
...
-  case 'GET_TRANSFER_HISTORY_FULFILLED':
-    return {
-      ...state,
-      transferHistory: action.payload
-    }
+    case 'GET_TRANSFER_HISTORY_FULFILLED':
+      return {
+        ...state,
+        transferHistory: action.payload
+      }
```
Comment (timothywangdev) [inline src/reducers/transferReducer.js]: no touch

File: src/reducers/walletReducer.js [hunk 27]
```diff
@@ -3,6 +3,7 @@
  */
 
 import update from 'immutability-helper'
+import { REHYDRATE } from 'redux-persist/lib/constants'
```
Comment (timothywangdev) [inline src/reducers/walletReducer.js]:
```suggestion
```

File: src/components/WalletSelectionComponent.jsx [hunk 28]
```diff
@@ -89,24 +87,35 @@ class WalletSelectionComponent extends Component {
...
+          <Grid item>
+            <Typography className={classes.connectedtext}>Synchronizing Acoount Info</Typography>
+          </Grid>
         </Grid>
-        <Grid item>
-          <Typography className={classes.connectedtext}>Account retrieved, your balance: {
-            numeral(utils.toHumanReadableUnit(wallet.accounts[0].balance[cryptoType])).format('0.000a')} {getCryptoSymbol(cryptoType)}
-          </Typography>
+      )
+    } else if (wallet && wallet.crypto && wallet.crypto[cryptoType] && wallet.crypto[cryptoType][0] && !actionsPending.syncAccountInfo) {
```
Comment (timothywangdev) [inline src/components/WalletSelectionComponent.jsx]: wallet.crypto is never null or undefined, see https://github.com/ventureum/Chainsfer/blob/fa1cfab611a818c0f368af9dea63361ea0fed612/src/reducers/walletReducer.js#L24

File: src/reducers/walletReducer.js [hunk 29]
```diff
@@ -34,24 +35,34 @@ export default function (state = initState, action) {
   switch (action.type) {
     // metamask
     case 'CHECK_METAMASK_CONNECTION_FULFILLED':
-      return update(state, { wallet: { metamask: { $set: action.payload } } })
+      return update(state, { wallet: { metamask: { $merge: action.payload } } })
```
Comment (timothywangdev) [inline src/reducers/walletReducer.js]: metmask payload has to overwrite wallet data, no touch

File: src/reducers/walletReducer.js [hunk 30]
```diff
@@ -34,24 +35,34 @@ export default function (state = initState, action) {
...
       } } } })
     // escrow wallet actions
     case 'VERIFY_PASSWORD_FULFILLED':
     // store decrypted wallet
       return update(state, { escrowWallet: { decryptedWallet: { $set: action.payload } } })
     case 'CLEAR_DECRYPTED_WALLET':
       return update(state, { escrowWallet: { decryptedWallet: { $set: null } } })
+    case 'SYNC_LEDGER_ACCOUNT_INFO_FULFILLED':
+      return update(state, { wallet: { ledger: { crypto: { $merge: action.payload } } } })
+    case REHYDRATE:
```
Comment (timothywangdev) [inline src/reducers/walletReducer.js]: why do we need this step?

File: src/utils.js [hunk 31]
```diff
@@ -24,17 +24,17 @@ function toBasicTokenUnit (val, decimals = 18, precision = 3) {
...
-  let gasPrice = await _web3.eth.getGasPrice()
+  let price = await _web3.eth.getGasPrice()
   let gas = (await _web3.eth.estimateGas(txObj)).toString()
-  let costInWei = (new BN(gasPrice).mul(new BN(gas))).toString()
-  let costInEther = _web3.utils.fromWei(costInWei, 'ether')
+  let costInBasicUnit = (new BN(price).mul(new BN(gas))).toString()
+  let costInStandardUnit = _web3.utils.fromWei(costInBasicUnit, 'ether')
 
-  return { gasPrice, gas, costInWei, costInEther }
+  return { price, gas, costInBasicUnit, costInStandardUnit }
```
Comment (timothywangdev) [inline src/utils.js]: inconsistent type for costInStandardUnit, here we have **string**,  but we have **float** in other places, see https://github.com/ventureum/Chainsfer/blob/fa1cfab611a818c0f368af9dea63361ea0fed612/src/actions/transferActions.js#L52

File: src/actions/transferActions.js (hunk 3 above)
Comment (InVincible2016) [reply src/actions/transferActions.js]: wallet.ledger.crypto will not be null, it's initialized to be {}

Comment (InVincible2016) [reply src/actions/transferActions.js]: I dont think putting the addressPool (aka addresses that have utxos) inside the txRequest is reaonable. It's not part of the txRequest, but rather side infomation to complete txRequest.

File: src/actions/walletActions.js (hunk 5 above)
Comment (InVincible2016) [reply src/actions/walletActions.js]: Forgot to remove. fixed.

File: src/reducers/walletReducer.js (hunk 27 above)
Comment (InVincible2016) [reply src/reducers/walletReducer.js]: This is needed.

File: src/reducers/walletReducer.js (hunk 29 above)
Comment (InVincible2016) [reply src/reducers/walletReducer.js]: This will overwrite existing data, but keeps other data that's not in the payload.

File: src/reducers/walletReducer.js (hunk 30 above)
Comment (InVincible2016) [reply src/reducers/walletReducer.js]: To initiate other initial states in redux, as we discussed.

File: src/utils.js (hunk 31 above)
Comment (InVincible2016) [reply src/utils.js]: fixed

File: src/ledgerSigner/index.js (hunk 21 above)
Comment (InVincible2016) [reply src/ledgerSigner/index.js]: Will do in next commit on Ledger ERC20 tx.
