### PR TITLE
Resolve #363, #365, #368

### LINKED ISSUE #363: Missing key for child element
steps to reproduce:

1. go to home page
2. login

### PR DESCRIPTION
**Pull request by InVincible2016**

### CODE REVIEW

File: src/components/WalletComponent.jsx [hunk 1]
```diff
@@ -336,7 +336,7 @@ class WalletComponent extends Component {
         <DialogTitle>Address</DialogTitle>
         <DialogContent>
           <Typography className={classes.addressDialog} align='left'>
-            {wallet.crypto[selectedCryptoType][0].address}
+            0x{wallet.crypto[selectedCryptoType][0].address}
```
Comment (timothywangdev) [inline src/components/WalletComponent.jsx]: must check if it's eth based address first. BTC address does not need 0x
